# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy Next.js app to Azure Web App - tech0-gen-11-step3-2-py-29

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # デプロイに不要なものを除外して成果物をまとめる
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .
            !node_modules/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "tech0-gen-11-step3-2-py-29"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A5BB0E69352A45D49D5EA061C0C79F6D }}
